app:
  telegram-token: ${TELEGRAM-TOKEN}
springdoc:
  swagger-ui:
    path: /swagger-ui
spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  datasource:
    url: jdbc:postgresql://localhost:5432/ChangeTracker
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

