app:
  telegram-token: ${TELEGRAM-TOKEN}
springdoc:
  swagger-ui:
    path: /swagger-ui
spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

